### ISSUE TITLE
Add exec* family

### ISSUE THREAD

**Issue by erikbor** [riboseinc/retrace#10]

**Comment by maheitsec** [comment]
Hello

I'd like to confirm exec* family functions.
execl
execv
execle
execve
execlp
execvp
Is that all?

**Comment by erikbor** [comment]
execve() is already implemented so you can skip that one. Please implement the others and use a similar approach of displaying argv[] (where applicable) as we have done in execve().

cheers!

**Comment by maheitsec** [comment]
int execl(const char *path, const char *arg0, ... /*, (char *)0 */);
I can get all parameters using va_list, but I can the real function using va_list as parameters.
So I'm going to make the char *argv[] and call execv function.
int execv(const char *path, char *const argv[]);
What do you think?

**Comment by erikbor** [comment]
Yes good approach.
execl and execv both replace the calling process image with a new process image.

Thanks!

**Comment by maheitsec** [comment]
Hello, Following functions were implemented.
execl, execv, execle, execve, execlp, execvp
I'm going to test these before merging to master.
Could you please let me know how to test these and test case exactly?

**Comment by erikbor** [comment]
We use Cmocka for testing purposes: [Cmocka](https://cmocka.org/)
Please have a look at the existing test:
```sh
test/cmockatest.c
```
You can integrate your tests in there. For testing exec* I think we can use '/usr/bin/id' because that would also be a good test case for the getuid() redirection.

**Comment by maheitsec** [comment]
Hello
I implemented 6 functions(execl, execv, execle, execve, execlp, execvp), but now I'm seeing new functions:
execvpe, fexecve, execveat
Should I implement them, too?

**Comment by erikbor** [comment]
Implemented. Thanks!
