### ISSUE TITLE
Doesn't support OS X 10.12?

### ISSUE THREAD

**Issue by catap** [riboseinc/retrace#142]
Hey,

I just tried the last master version (413fdbc25ac280459b424330235816587e548ed4) and it doesn't work on my macOS 10.12.5.

```
➜  retrace git:(master) ./autogen.sh
....
➜  retrace git:(master) ./configure
....
➜  retrace git:(master) make
...
➜  retrace git:(master) ./retrace -f ./retrace.conf.example /usr/bin/id 
uid=501(catap) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),501(access_bpf),33(_appstore),100(_lpoperator),204(_developer),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh)
➜  retrace git:(master) 
```

I've tried to changed config to:
```
getuid,20
geteuid,20
```

and nothing changes.

@ronaldtse or someone can confirm that it isn't expected behaviour?

**Comment by riataman** [comment]
@catap: Unfortunately macOS strips the relevant environment variables needed to inject retrace for system binaries.

If you copy /usr/bin/id to your home dir and run it from there, then it works.

**Comment by catap** [comment]
@riataman, yay! thanks!

**Comment by riataman** [comment]
I guess we can keep this one open with the goal of properly document this limitation.

**Comment by catap** [comment]
and you're absolutely right. It removed all `DYLD_` and `LD_LIBRARY_PATH` variables for restricted process when SIP is enabled.

**Comment by catap** [comment]
LOL

```
dtrace: failed to execute /usr/bin/id: dtrace cannot control executables signed with restricted entitlements
```

**Comment by riataman** [comment]
All of this so you won't stole those itunes songs :)

**Comment by catap** [comment]
@riataman but I can run `csrutil disable` and disable it :)
