### ISSUE TITLE
Add gethostbyname, gethostbyname2, gethostbyaddr, gethostent, sethostname, sethostent, endhostent, herror, hstrerror

### ISSUE THREAD

**Issue by erikbor** [riboseinc/retrace#149]
The above is copied straight from the macOS man page so maybe some functions are not available on Linux.

Please print the returning struct in a similar fashion as we do with envp in exec.c

And please add tests. Thanks.

**Comment by jjr840430** [comment]
@erikbor Those functions were already added in sock.c.

**Comment by erikbor** [comment]
You are right! Sorry didn't see those in the branch I was working in. Closing this issue therefor.
