### ISSUE TITLE
Make a homebrew-retrace formula

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/retrace#151]
Just like https://github.com/riboseinc/homebrew-rnp , a formula to install retrace via:

```sh
brew tap riboseinc/retrace
brew install retrace
```

**Comment by catap** [comment]
I can do it

**Comment by ronaldtse** [comment]
@catap do you plan on doing this or should someone else do it? Thanks!

riboseinc/homebrew-retrace#1

**Comment by ronaldtse** [comment]
I think @wizzard is going to do it. Thanks!

**Comment by ronaldtse** [comment]
@wizzard it's been a while -- @jjr840430 could you help do this formula? Thanks!

**Comment by jjr840430** [comment]
@ronaldtse The `homebrew` for `retrace` was already created [here](https://github.com/riboseinc/homebrew-retrace)

**Comment by ronaldtse** [comment]
Oh my memory... closing!
