### ISSUE TITLE
gcc crashes when run under retrace

### ISSUE THREAD

**Issue by riataman** [riboseinc/retrace#152]
```
$cat test.c
#include <stdio.h>

int main(void)
{
        printf ("Hello word\n");

        return 0;
}
$ ./retrace gcc test.c
.......
gcc: internal compiler error: Segmentation fault (program as)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
jpablo@jessie:~/l/retrace$ cat test.c
```

**Comment by riataman** [comment]
@drystone:

This is crashing in the bfd (Binary File Descriptor Library) library when invoked by 'gas'. I downloaded binutils-2.28 source code and they have a functions named real_fopen real_fseek, etc, and we are making this crash.

The other option would be to mark our versions with __attribute__((visibility("hidden"))) to avoid exporting it. Not sure if that would work.

**Comment by drystone** [comment]
@riataman I think hiding would definitely work. All our internal functions ought to be hidden. It's not surprising we've stumbled upon name clashes!

**Comment by riataman** [comment]
fixed
