### ISSUE TITLE
Follow fork/exec

### ISSUE THREAD

**Issue by catap** [riboseinc/retrace#169]
Hey,

I've trying to trace something and just realise that `retrace` doesn't support `following-children` mode (likes `strace -f`).

`dtruss` and `strace` have a following mode that adds `<pid>` to output and trace also all subprocess that was created by `fork` or `exec*`.

I think it is expected features to tracing utils.

**Comment by riataman** [comment]
I think this is the same as https://github.com/riboseinc/retrace/issues/104

**Comment by catap** [comment]
yes, looks so
