### ISSUE TITLE
memcpy(), memmove(), bcopy(), memccpy() function

### ISSUE THREAD

**Issue by jjr840430** [riboseinc/retrace#180]
@catap 
What do you think about tracing memcpy() function?

**Comment by catap** [comment]
Well.. It's nice to have :) Also if you're implement `memcpy`, you can also implement: `memmove`, `bcopy`,  and `memccpy`.

Plus I keep in mind that using `memcpy` when you should use `memmove` makes strange bug likes [this](https://bugzilla.redhat.com/show_bug.cgi?id=638477)

**Comment by jjr840430** [comment]
OK, Thanks for your advise.
