### ISSUE TITLE
fwrite() binary data printf error

### ISSUE THREAD

**Issue by jjr840430** [riboseinc/retrace#185]
(5638) fwrite(0x559d93ce8f41, 1, 25, 0x559d9459c4b0 [fd 4], ) = 25
	0000000	 23                                                | #
	0000000	 20                                                |  
	0000000	 45                                                | E
	0000000	 64                                                | d
	0000000	 69                                                | i
	0000000	 74                                                | t
	0000000	 20                                                |  
	0000000	 61                                                | a
	0000000	 74                                                | t
	0000000	 20                                                |  
	0000000	 79                                                | y
	0000000	 6f                                                | o

**Comment by riataman** [comment]
@jjr840430 That looks good to me. The fwrite call is requesting to print 25 buffers of size 1.

I guess we can special case the case where size = 1

**Comment by jjr840430** [comment]
Can you try ./retrace wget https://www.google.com?

**Comment by riataman** [comment]
YeahI agree that is kind of ugly, I would special case the handling of PARAMETER_TYPE_MEM_BUFFER_ARRAY for when size = 1 not to print the buffers separately.

**Comment by jjr840430** [comment]
@riataman It's very much lines for tracing fwrite() call.
I think it's convenient way to print the tracing result like as read/write call.
