### ISSUE TITLE
./retrace shell script error

### ISSUE THREAD

**Issue by jjr840430** [riboseinc/retrace#187]
dev@dev-virtual-machine:~/work/Retrace/GitWork/retrace$ ./retrace ./test/mytest
./retrace: 45: ./retrace: [[: not found
./retrace: 62: ./retrace: [[: not found

**Comment by erikbor** [comment]
@jjr840430 what is the operating system you are testing on and to which package does your /bin/sh belong to?

**Comment by jjr840430** [comment]
I'm using Ubuntu16.04 64bit Desktop. Also the /bin/sh is symlinked into /bin/dash.

**Comment by wizzard** [comment]
weird, I'll take a look.
