### ISSUE TITLE
Remove locking

### ISSUE THREAD

**Issue by catap** [riboseinc/retrace#208]
The basic idea how we can increase performance of retrace it is remove all locking from the code or made it as smaller time as we can — to open log file.

How we can do it? rewrite all `retrace_print*` function to write to static buffer and print the buffer to output at one `write` at end of `retrace_event`.

I expect that it decrease performance impact of retrace for application.

cc: @riataman @ronaldtse

**Comment by catap** [comment]
After https://github.com/riboseinc/retrace/pull/207 will be merged it should be much easy :)

**Comment by riataman** [comment]
fixed
