### ISSUE TITLE
Extract CMocka detection into m4 macro

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/retrace#215]
There is Cmocka detection code inside `configure.ac` but it should be extracted into a separate m4 file in `m4/ax_check_cmocka.m4`. See practice in riboseinc/rnp#265

**Comment by ronaldtse** [comment]
@jjr840430 could you help handle this? It should just be a copy / paste from rnp. Thanks.

**Comment by jjr840430** [comment]
@ronaldtse OK, I will implement that.

**Comment by jjr840430** [comment]
Refer pull request #271

**Comment by ronaldtse** [comment]
Completed in #271. Thanks @jjr840430 !
