### ISSUE TITLE
Executable wrapping with retrace

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/retrace#218]
Generating an executable that wraps the original executable to produce predictable behavior without needing to type `LD_PRELOAD` every time. For example, a re-skinned Firefox for normal users.

**Comment by erikbor** [comment]
Once we distribute retrace as an package then we cannot assume that the target system has a C compiler installed to perform this wrapping. Maybe we could get away with building a light weight `retrace.in`-like template that can be turned into a target wrapper?

**Comment by riataman** [comment]
I think this is done for v2
