### ISSUE TITLE
OpenBSD build fails: common.c:59:22: error: execinfo.h: No such file or directory

### ISSUE THREAD

**Issue by erikbor** [riboseinc/retrace#225]
@jjr840430 building on OpenBSD now fails because execinfo.h is not present on OpenBSD

execinfo.h got included in [221](https://github.com/riboseinc/retrace/pull/221)

Can you please have a look. Thanks.

**Comment by jjr840430** [comment]
@erikbor I don't have OpenBSD. :(
Can you try compile it without that header?
This header is required for backtrace() function.

**Comment by erikbor** [comment]
@riataman can you help Jin please?

**Comment by wizzard** [comment]
I'm able to compile the project without execinfo.h header, I'll fix that issue.

**Comment by riataman** [comment]
I can swear that I had removed that header in my last openbsd patch ...

**Comment by wizzard** [comment]
@riataman do you want to remove that header completely from common.c or I can add a conditional include (include this header if it's present in the system)

**Comment by riataman** [comment]
I don't even know why it was added. if it builds everywhere without it I guess we can just purge it.

**Comment by wizzard** [comment]
Ok, then just remove that. 
But if anyone needs to add a system specific header (such as execinfo.h), please use a conditional include, so the build doesn't fail on other systems.

**Comment by jjr840430** [comment]
Sorry, It was added by me :(
