### ISSUE TITLE
create a tool to inject strings into binary files

### ISSUE THREAD

**Issue by erikbor** [riboseinc/retrace#249]
This is an external tool to inject strings into binary files that are parsed by executables that are retraced. Eventually this functionality should be in retrace itself in fread etc.

I'd like to fuzz a whole bunch of operating systems handling of disk images, ELF files, image files etc and use retrace to see what's happening.

**Comment by erikbor** [comment]
this is the stringinjector work

**Comment by ronaldtse** [comment]
@jjr840430 since stringinject is working now, we should merge that into retrace binary for on-the-fly modification of file syscalls content, such as via fopen (so we don't need to pregenerate the files anymore).

**Comment by jjr840430** [comment]
@ronaldtse OK, What's the option to integrate stringinjector into retrace?
By linking as library or executing as independent utility?

**Comment by ronaldtse** [comment]
@jjr840430 we should integrate stringinjector functionality in file-io fuzzing and net-io fuzzing, then we don't need a separate stringinjector utility?

@erikbor could elaborate more?

**Comment by jjr840430** [comment]
@ronaldtse You are right. I will try to integrate stringinjector into retrace IO fuzzing.

**Comment by erikbor** [comment]
We still want to have a separate string injector utility so we can fuzz static linked binaries and kernels.
But the logic of the generation of long strings, format strings, and corrupt headers (changed bytes) can live in a function that is used by both retrace (for net-io and file-io) and the string injector utility.

**Comment by ronaldtse** [comment]
Yes @erikbor is exactly right. The separate utility should probably link (or includes) libretrace!

**Comment by jjr840430** [comment]
@ronaldtse @erikbor I will make source files to include string injector functions in libretrace.

**Comment by ronaldtse** [comment]
@jjr840430 or should we do it the other way around?

* include stringinjector functions in retrace lib
* stringinject executable should include retrace lib

**Comment by jjr840430** [comment]
Including stringinjector functions in retrace lib is possible and seems easy.
But not sure it's possible whether stringinject executable include retrace lib :)

**Comment by jjr840430** [comment]
@ronaldtse @erikbor Can you review the following README for stringinject in retrace?
https://github.com/riboseinc/retrace/blob/stringinjector/examples/stringinject/README.md

**Comment by erikbor** [comment]
Looks good to me! Can you rename the 'position' to 'offset' please (and also in the source code)? That way we are fully in line with tools such as hexdump etc.

**Comment by jjr840430** [comment]
@erikbor Thanks for your reviews. I will modify so. Thanks.

**Comment by jjr840430** [comment]
@ronaldtse @erikbor When injecting format string, overflow buffer and file line, is there any requirement for source stream?
i.e. Above injections may have meaning when source buffer or stream is ascii data.

**Comment by erikbor** [comment]
@jjr840430 Yes you are correct. But I think for now it's best to just insert it regardless of what type of stream it is. In the future it would be great to take into account things like encoding etc but we'd like to have the basic functionality as soon as possible :) We are very eager to start fuzzing. Making things better + enhancing can come later.

**Comment by jjr840430** [comment]
ok, will do

**Comment by ronaldtse** [comment]
This seems att done with #256!
