### ISSUE TITLE
Socket IO fuzzing

### ISSUE THREAD

**Issue by jjr840430** [riboseinc/retrace#250]
The configuration for network IO will be as followings:

fuzzing-net-io,[function name],[IO fuzzing type],[position],[count],[fuzzing rate]

- Function name
send, sendto, sendmsg, write
- IO fuzzing type
ASCII_STRING, FORMAT_STRING, GARBAGE, RANDOM_STRING
- position
'position' is the position value to be inserted. If position is over than length of buffer, then fuzzing will be ignored.
- count
'count' is the number of the value to be inserted. If inserted buffer is overflow IO buffer, then it will be truncated into available size at run-time.

**Comment by ronaldtse** [comment]
@jjr840430 when do you estimate we have our first PR? Thanks.

**Comment by jjr840430** [comment]
@ronaldtse This part was almost implemented, but needs some testing still.
Will make PR soon.

**Comment by jjr840430** [comment]
That was implemented by #256

**Comment by ronaldtse** [comment]
Let's close this since #256 is merged. Thanks!
