### ISSUE TITLE
Change make install prefix from '/usr' to '/usr/local' to fix installation on macOS with SIP (enabled by default)

### ISSUE THREAD

**Issue by erikbor** [riboseinc/retrace#251]
SIP which is enabled by default macOS does not allow us to write in /usr/bin. I'd like to have the Makefile prefix changed from /usr to /usr/local so we can make install on macOS:

```sh
$ uname -a
Darwin foobar.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
$ sudo make install
Password:
Making install in test
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
 ./install-sh -c -d '/usr/bin'
 /usr/bin/install -c retrace '/usr/bin'
install: /usr/bin/retrace: Operation not permitted
make[2]: *** [install-dist_binSCRIPTS] Error 71
make[1]: *** [install-am] Error 2
make: *** [install-recursive] Error 1
$ 
```

**Comment by erikbor** [comment]
@wizzard @drystone

You guys alright with this?

**Comment by ronaldtse** [comment]
We can enable this behavior specifically for macOS as well.

**Comment by drystone** [comment]
@erikbor yes. I seem to remember discussing this before. `/usr/local` is the standard for locally installed packages (those outside the control of the package manager)

**Comment by erikbor** [comment]
@drystone can you make this change then please?

**Comment by wizzard** [comment]
@erikbor I fixed the default installation prefix to /usr/local as requested,
but please note: this won't fix your problem with permissions (/usr/local is usually writable by root user only)

**Comment by erikbor** [comment]
@wizzard thanks for that!!!

The issue on macOS is that SIP prevents writes to /usr/bin even as root. /usr/local/bin otoh is not protected by SIP so sudo make install will work. Typically /usr/local/bin will be writeable for your desktop user anyway as it's the symlink target for brew its installed packages.
