### ISSUE TITLE
File I/O fuzzing

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/retrace#255]
Fuzzing File I/O via file system calls:
* fopen, fdopen, freopen
* fread
* fwrite
* fclose, fcloseall

Related to functionality in `stringinject` #249

**Comment by jjr840430** [comment]
@ronaldtse @erikbor 
I'm not sure how apply stringinject into fopen, fdopen, freopen.

Are you planning to replace file contents with injected buffer before calling fopen()?

**Comment by erikbor** [comment]
I didn't see this issue before but fopen/fdopen/freopen/fclose/fcloseall indeed cannot have string inject. Please skip those.

**Comment by jjr840430** [comment]
@erikbor If retrace injects strings before calling fopen, then it would have more efficiency than injecting  while calling fread/fwrite.
I think that option would be helpful too.

**Comment by erikbor** [comment]
So you're saying that we should fuzz strcpy/strncpy/sprintf/snprintf/strlcpy/strcat? The thing I'm worried about is when taking that we'd modify buffers that are used by the program and will crash the program we are fuzzing. Because how would you identify the buffer that is going to be used in the send/write/read?

**Comment by jjr840430** [comment]
@erikbor I didn't say to fuzz string functions.
That's mean that retrace may inject strings into a file which is called by fopen() while hooking fopen() function.

**Comment by erikbor** [comment]
@ronaldtse what do you think?

**Comment by ronaldtse** [comment]
My intention was:

* fread: the content that is read out is fuzzed - meaning that retrace will run `real_fread` but occasionally fuzz some content (and length returned).
* fwrite: content that is written is fuzzed (and length).
* fopen: as @jjr840430 mentioned we can read in the whole file and proxy the file descriptor for fuzzed content. Also simulate error conditions.
* fclose: simulate error conditions.

**Comment by jjr840430** [comment]
@ronaldtse What do you think about that?
https://www.ribose.com/#spaces/40b2063b-ccf5-484f-9fe9-fb7ffcafbedd/conversation/conversations/7866518f-9410-5acd-b3cd-70178d9c9020

So we may extend retrace fuzzing functions into almost system calls by specified fuzzing types on above link.

**Comment by ronaldtse** [comment]
I agree with the approach, as long as we keep fuzzing options independent on each area.
