### ISSUE TITLE
macOS CMocka test failure

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/retrace#276]
Here's the rather large log file!

[test-suite.log.zip](https://github.com/riboseinc/retrace/files/1229175/test-suite.log.zip)

**Comment by jjr840430** [comment]
@drystone As I mentioned before, rtr_get_config_multiple() function was failed on mac os.
Can you please look test-suite.log.zip?

**Comment by jjr840430** [comment]
related with pull request #277

**Comment by ronaldtse** [comment]
Fixed in #277 , thanks!
