### ISSUE TITLE
CI coding style check

### ISSUE THREAD

**Issue by efiop** [riboseinc/retrace#28]
As it was previously discussed, we should use BSD coding style[1]. To enforce that, it would be nice to have travis check it automatically.

[1] https://www.freebsd.org/cgi/man.cgi?query=style&sektion=9

**Comment by ronaldtse** [comment]
We've now added clang-format in a git pre-commit hook script, so if Travis can check if the code is correctly formatted it would be great. Thanks @efiop !

**Comment by efiop** [comment]
Added checkpatch.pl as a temporary measure in #96

**Comment by riataman** [comment]
I think what we have now is good enought
