### ISSUE TITLE
OpenBSD build is broken

### ISSUE THREAD

**Issue by riataman** [riboseinc/retrace#293]
STAILQ_* doesn't seem to exist in OpenBSD. 

See http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/sys/sys/queue.h?annotate=1.44

**Comment by drystone** [comment]
Could you try [this branch](https://github.com/riboseinc/retrace/tree/openbsd-stailq) please

**Comment by drystone** [comment]
@riataman ... or do you think it would be better to have `openbsd-specific.h` etc. to avoid too much cruft in `configure.am` and `config.h`?

**Comment by riataman** [comment]
@drystone made it advance a little more, but now its breaking because there's no -Wno-unused-result in the old version of gcc that OpenBSD ships with (4.2.1).

**Comment by drystone** [comment]
Which OpenBSD are we targetting? 6.1 has GCC4.9.4

**Comment by riataman** [comment]
Is that true? I have OpenBSD 6.1 and it has gcc 4.2.1. 

Maybe 4.9 is available in ports, but certainly doesn't seem to be part of the the base system.

**Comment by drystone** [comment]
Strange. I've tried 5.9 and 6.1 from the repos (no ports) and I have gcc 4.9 on both?

**Comment by drystone** [comment]
You need `pkg_add gcc`. I'm fairly sure this was all you needed on 6.1 but 5.9 requires a change to `configure.ac` as the binary is `egcc`. I've uploaded a patch to `openbsd-stailq`. So it builds, but doesn't work ;) I'm away until next week so won't be able to dig deeper for a few days.
