### ISSUE TITLE
Introduce an overwrite option for stringinject INJECT_FORMAT_STR, stringinject INJECT_SINGLE_HEX and stringinject INJECT_FILE_LINE

### ISSUE THREAD

**Issue by erikbor** [riboseinc/retrace#306]
The `stringinject` function currently **inserts** `INJECT_FORMAT_STR`, `INJECT_SINGLE_HEX` and `INJECT_FILE_LINE`. So when `buf` is something like `this is my string` (len 17 bytes) and we `stringinject` `INJECT_FORMAT_STR` at offset 2 with a count of 2 the resulting `buf` will be: `thi%s%ss is my string` (len 21 bytes).

Can you please introduce an **overwrite** option to these 3 string injects.
This is to prevent packet sizes from growing and we will be able to surgically replace a particular string in `send()` and `sendto()` etc. The `buf` example mentioned earlier would look something like this: `thi%s%s my string` (len 17 bytes).

@drystone do you have time for this?

**Comment by erikbor** [comment]
In case the `buf` size is not big enough to hold the injected strings then truncating the injected string is alright.

**Comment by drystone** [comment]
@erikbor sure. We'll need to add a `replacecount` parameter (or `replace` boolean). Should I adjust the existing syntax or add a new injection type?

**Comment by erikbor** [comment]
@drystone what ever you think makes the most sense! Thanks a lot, this will be a killer feature :D

**Comment by erikbor** [comment]
@drystone could you also come up with an example for the `/examples` directory? Cheers

**Comment by drystone** [comment]
Yes, will do, currently working on some tests too.

**Comment by erikbor** [comment]
@drystone Hi John, I just had the opportunity to thoroughly test your recent commits and I am wondering how I can define wether the overwrite at pos should happen or not.

Another question I have is what does `STRINJECT_TYPE_STANDARD` do?

Cheers

**Comment by erikbor** [comment]
@drystone John, can you give an update regarding the overwrite option please? We're already using Retrace in real life fuzzing of NSD and it would be great if we can also include fuzzing without altering the packet size. Thanks!

**Comment by drystone** [comment]
@erikbor not got around to documenting yet but meantime, please see comment at #307 and look at [`test/strinject.sh`](https://github.com/riboseinc/retrace/blob/master/test/strinject.sh) and [`test/strinject.c`](https://github.com/riboseinc/retrace/blob/master/test/strinject.c) for reference

**Comment by erikbor** [comment]
@drystone I have tested your commit extensively and ran a fuzzing session which took 4 hours and generated over 1 million DNS requests. No failures and the output was exactly as expected. Your `OR|XOR|AND` additions worked extremely well. Thanks for that!!! 👍 

I have enough operational experience now with these additions that I'll write the documentation.
