### ISSUE TITLE
Example for DNS zone transfers

### ISSUE THREAD

**Issue by erikbor** [riboseinc/retrace#320]
@jjr840430 

Can you write a light DNS zone transfer (AXFR) utility with the following syntax:

```sh
./axfr <nameserver> <domain>
```

And:
* TCP
* It should support both ipv4 and ipv6
* It should use `send()` (so we can fuzz it)
* It should display the results from `recv()`
* TSIG etc is not needed for now

Do you have time for this? :)

**Comment by erikbor** [comment]
I will write the example README.md and the corresponding tests so no need for those.

**Comment by erikbor** [comment]
@jjr840430 btw, we will use this for NSD fuzzing

**Comment by jjr840430** [comment]
@erikbor I will build this utility from today :) Thanks.

**Comment by erikbor** [comment]
@jjr840430 nice one!!! thanks!!!

this has priority over writing the approach 👍

**Comment by jjr840430** [comment]
@erikbor I researched some open sources to build light utility to transfer DNS zones.
Can we use `host`(`bind9`) or `nsd-control` utility?

Those utilities are some complex to build light individual utility due to some internal library dependencies.

From some tests, I noticed that it uses `read`/`write` syscalls and those functions may be fuzzed by current `retrace`.

If you agreed with those utilities, then I will add some example commands and fuzzing samples.

**Comment by erikbor** [comment]
@jjr840430 I think that the utilities mentioned can be used for the fuzzing efforts. But I'd like to have a utility that uses `sendto()` for the `AXFR`. I have the fuzzing framework to fuzz `sendto()` ready so the utility would be a drop in replacement for `query.c`. Having to modify it for `host` or `nsd-control` would result in duplicate work for my efforts. Bernstein wrote a document describing AXFR: [cr.yp.to](https://cr.yp.to/djbdns/axfr-notes.html). I was under the impression that this should be easy to implement. What do you think?

**Comment by jjr840430** [comment]
@erikbor OK, then I will work to build this utility from today. Thanks.

**Comment by ronaldtse** [comment]
BTW I think there are some newer points about AXRF in RFC 5936: https://tools.ietf.org/html/rfc5936

**Comment by jjr840430** [comment]
@erikbor I have implemented simple AXFR client in `examples/dns-fuzz/foward.c`.
Please review it and let me know your opinions. Thanks.

**Comment by erikbor** [comment]
@jjr840430 it works amazing, thank you so much! Can you merge it to master please?

**Comment by jjr840430** [comment]
@erikbor merged :)
