### ISSUE TITLE
Retrace release + formula

### ISSUE THREAD

**Issue by erikbor** [riboseinc/retrace#340]
Hi @jjr840430 

Can you please create a release for Retrace similar to what you've done for RVC?

Many thanks!!!

**Comment by jjr840430** [comment]
@erikbor Done.

**Comment by ronaldtse** [comment]
Thanks @jjr840430 !

**Comment by ronaldtse** [comment]
Formula updated at: https://github.com/riboseinc/homebrew-retrace/pull/4
