### ISSUE TITLE
Add strmode() for macOS

### ISSUE THREAD

**Issue by erikbor** [riboseinc/retrace#49]

**Comment by riataman** [comment]
@erikbor I'm missing something or the chmod modes between Linux (already implemented) and macOS are the same?

Or was this about doing the mode_t to string conversion that you already put in and we need to close this one?

**Comment by erikbor** [comment]
strmode() only exists on macOS and it would be great to be able to trace it with retrace too.

The trace_mode() function is used for displaying permissions in chmod() tracing (and possibly others in the future). Because of the lack of strmode() on Linux I implemented trace_mode() to avoid having to include the full BSD strmode() in retrace.
