### ISSUE TITLE
implement OpenSSL tracing

### ISSUE THREAD

**Issue by erikbor** [riboseinc/retrace#83]
As per Pablo's suggestion:

1. dump keys and secrets
2. dump the traffic before encryption and after decryption

**Comment by jjr840430** [comment]
@riataman, 

Are you going to trace all OpenSSL API functions?
OpenSSL has libcrypto and libssl libraries.

If you agreed, then can I work on tracing of libcrypto library?

**Comment by riataman** [comment]
Sure go ahead, I did the most important ones already: https://github.com/riboseinc/retrace/pull/92

**Comment by jjr840430** [comment]
Great, Wonderful!
So can I work on tracing of libcrypto library?

**Comment by riataman** [comment]
Yeah, go ahead

**Comment by jjr840430** [comment]
Also, I have developed plugin for redirection.
Can you review https://github.com/riboseinc/retrace/tree/issue_20 and let me know your opinions?
