### ISSUE TITLE
Make firefox work under retrace

### ISSUE THREAD

**Issue by riataman** [riboseinc/retrace#90]
Currently it will just hang before showing anything. Just picked up Firefox at random as an example of a very big program.

The other one I was using to test is gnumeric (or apparently any GTK+ app). That one just goes into a loop and core dumps.

**Comment by riataman** [comment]
This one is tricky. If found out that if I disable our getenv implementation firefox works fine (with a few extra fixes that I have).

For some reason dlsym calls "calloc" when run under firefox, which in turn calls (our implementation of) getenv and so we get into a deadlock.

**Comment by drystone** [comment]
@riataman - there was a bug in getenv if the environment variable didn't exist. I've just submitted a fix. How are you retacing firefox - when I try I get no output ... ?

**Comment by riataman** [comment]
yeah, the no output is the issue. I run it in gdb:

gdb /usr/bin/firefox
set env LD_PRELOAD = ./retrace.so
run
^C
where

You'll see its deadlocked in a stack that roughly looks like this:

dlsym()->calloc()->(our implementation of) getenv()->dlsym()->deadlock

(if /usr/bin/firefox is a script in your distro replace it for /usr/bin/firefox-esr)

For some reason Firefox calls to dlsym calls "calloc" which it doesn't in other programs, I browsed the glibc code a bit but didn't found a definitive answer, calloc was being called if some call to setup a per thread storage space failed (__libc_createkey something like that), I'm not sure why it fallbacks to that in firefox.

In the bright side with the latest code I submitted all the other graphics applications that I tested are working.

**Comment by drystone** [comment]
I guess at some point it's going to be worth having a good look at the dlsym implementation. The env bug probably wasn't the problem here. Is it deadlock or infinite loop? Deadlock doesn't seem likely as we don't hold any locks. Infinite loop doesn't seem likely as the stack would surely exhaust almost immediately. Something else?

**Comment by riataman** [comment]
It's deadlocked on internal dlsym locks. If those locks weren't there we would fall into an infinite loop. I have been pinging you in skype btw.

**Comment by riataman** [comment]
and yeah, the infinite loops aren't infinite, they core dump eventually :).

**Comment by ronaldtse** [comment]
This is a significant milestone -- thank you @riataman !

**Comment by riataman** [comment]
Yeah, I discovered that ltrace doesn't work with firefox :)
